name: GBP
on:
  pull_request_target:
    types: [closed, opened]
jobs:
  gbp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Pull GBP branch
      run: |
        git fetch origin gbp-balances

        # Make sure it's loaded
        git checkout gbp-balances

        # Go back to master
        git checkout master
    - name: GBP action
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}